### ISSUE TITLE
Timeout not respected for connection time.

### ISSUE THREAD

**Issue by subsidel** [bbc/melchett#21]
**Describe the bug**
The timeout configuration doesn't always timeout long requests.
As far as I can tell, this is due to how Axios handles its own timeout option.
Axios timeouts do not respect connection time, only response time.
This means that if the endpoint you are making a request to doesn't exist, or is misconfigured in some way, the timeout will not happen.

**To Reproduce**
1. Set a timeout via the options object, or use the default timeout.
2. Call any endpoint that will never respond, such as `GET https://example.com/does-not-exist`
3. Observe very long call time, until your runtime times it out (if ever).

**Expected behavior**
If an endpoint does not exist, the timeout still is respected, and the call is finished with an appropriate timeout error.

**Additional context**
A 3 year old issue on Axios:
https://github.com/axios/axios/issues/647

Commenter that explains the issue:
https://github.com/axios/axios/issues/647#issuecomment-322209906

Axios documentation on cancellation using `CancelToken` (as it is suggested in the issue):
https://github.com/axios/axios/blob/7df84a7ff7c2d33b0f210608a489db7b5fc0df37/README.md#cancellation

**Comment by Richard-Walton** [comment]
Just hitting this problem myself.  Very frustrating!

**Comment by jordanholt** [comment]
Cheers! Will look at getting a fix in place for this. We're about to release a new major version (see #22) so would you like the fix backported into 2.x too?

**Comment by WestonThayer** [comment]
I’d be fine upgrading to major for a fix.

**Comment by epatrasc** [comment]
Fix is now part of v3.0.1
